function jsHaritaCiz() {
    var map = L.map('map').setView([0.00085447747469, 28.514484565], 20);
    var baselayer = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // var mytile =L.tileLayer('file:///D:/Projeler/Abdi İbrahim/kat_cizim/proje_harita/5_00_kotu_kati_uretim/Mapnik/{z}/{x}/{y}.png', {
    //var mytile = L.tileLayer('05_00_kotu/{z}/{x}/{y}.png', {
    //maxZoom: 25,
    //tms: true,
    //attribution: 'Generated by QTiles'
    //}).addTo(map);


    var tile_04_50_kotu = L.tileLayer('04_50_kotu/{z}/{x}/{y}.png', {
        maxZoom: 25,
        tms: true,
        attribution: 'Aniventi'
    }).addTo(map);


    var tile_00_00_kotu = L.tileLayer('00_00_kotu/{z}/{x}/{y}.png', {
        maxZoom: 25,
        tms: true,
        attribution: 'Aniventi'
    }).addTo(map);

    var tile_05_00_kotu = L.tileLayer('05_00_kotu/{z}/{x}/{y}.png', {
        maxZoom: 25,
        tms: true,
        attribution: 'Aniventi'
    }).addTo(map);


    // var layerControl = L.control.layers({ 'Basemap': mytile }, { '05_00_kotu': mytile }).addTo(map);
    var layerControl = L.control.layers().addTo(map);
    layerControl.addBaseLayer(tile_04_50_kotu, "04_50_kotu");
    layerControl.addBaseLayer(tile_00_00_kotu, "00_00_kotu");
    layerControl.addBaseLayer(tile_05_00_kotu, "05_00_kotu");
}
